/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Berg(props) {
  const { nodes, materials } = useGLTF('./models/Berg.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Berg.geometry} material={materials.Berg} />
      <group position={[0.648, 7.115, 0.756]} rotation={[0, 0.256, 0]} scale={1.05}>
        <mesh
          geometry={nodes.Sphere001.geometry}
          material={materials.Iris}
        />
        <mesh
          geometry={nodes.Sphere001_1.geometry}
          material={materials.ojo}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/Berg.glb')
